### ISSUE TITLE
About some ideas

### ISSUE THREAD

**Issue by GaoXanSheng** [svenar-nl/PowerCamera#3]
In some custom server clients, there is no playerjoin event. Even if this configuration is closed in the configuration file, she will still report an error. It looks like this:

[Server thread/ERROR]: Could not pass event PlayerJoinEvent to PowerCamera v0.5

org.bukkit.event.EventException: null

So can you judge when the plug-in starts and not register events?

**Comment by greatericontop** [comment]
"In some custom server clients" PR only really is guaranteed to work on bukkit/spigot/paper/etc servers. You can fork the project and remove the events manually if you want.
